### PR TITLE
Feature/file sent icon in webchat

### PR DESCRIPTION
**Pull request by ragini01**
I have added an attach file icon in Webchatwidget. when a user requests for file upload, after a successful upload you will now see the uploaded details in Webchat widget which contains attached file name and an icon to indicate that this message contains an attachment. This is how it looks now,
Screenshot from 2022-06-14 00-55-56

### CODE REVIEW

**Comment by cbuchwald** [comment]
You forgot to add this dependency to package.json: "@cognigy/webchat": "git+https://git@github.com/Cognigy/WebchatWidget.git#v2.41.1",

**Comment by ragini01** [comment]
> You forgot to add this dependency to package.json: "@cognigy/webchat": "git+https://git@github.com/Cognigy/WebchatWidget.git#v2.41.1",

@cbuchwald I have added package.json with the required changes.

**Comment by EgleHelms** [comment]
@ragini01 There are still some conflicts in the branch, can you please resolve them, so we can approve? Since the functionality is working and the code looks good to me :)

**Review by EgleHelms — APPROVED** [review]
Works as expected :)

**Review by cbuchwald — APPROVED** [review]

**Pull request merged**
